name: aplikacje_bd
channels:
  - conda-forge
  - defaults
dependencies:
  - sqlalchemy
  - pycryptodome
  - pip
  - python=3.13
  - requests
  - pytest
  - html-sanitizer
  - markdown
  - passlib
  - pip:
    - flask
    - flask_login
    - Flask-SQLAlchemy